### ISSUE TITLE
Role assignment to super admin doesn't seem to work

### ISSUE THREAD

**Issue by teejeer** [NeosIT/active-directory-integration2#3]
When I make an ldap profile where one AD group maps to the wordpress super admins role it doesn't seem to do anything. The user logs in and they aren't assigned that role. 

All the other AD group to Wordpress Roles work.

**Comment by schakko** [comment]
Thank you, we can confirm this issue and put it into our backlog.

**Comment by SebastianWe** [comment]
This issue has been fixed in the latest version.

**Comment by teejeer** [comment]
I got a fresh clone of the code this morning. It still doesn't work.

**Comment by SebastianWe** [comment]
We pushed our latest changes about 19 ~ 20 hours ago. Did you clone after that?

**Comment by schakko** [comment]
@teejeer Can you post an excerpt from the *Test authentication* tool?
I could also not reproduce the issue.

From the documentation:

- As mentioned, the role super admin can only be assigned inside a Multisite environment.
- Because of security reasons the role super admin can only be assigned in a profile configuration and not in site configuration. You will see an error message if you try to assign the role inside a site configuration.
- After a user with role "super admin" has been synchronized for the first time he is added to the admin user list in WordPress Multisite

**Comment by teejeer** [comment]
In my testing environment I have to do hosts file records to go against different versions of our dev/test/prod instances. Plus I also have a second dev instance. I was pointed at a different instance. It looks like your fix did work. My bad.

Thanks for your work.

**Comment by schakko** [comment]
Glad to hear that ;-)
Thank you!
